name: Build docs and push to docs branch

on:
  workflow_dispatch:
  release:
    types: [ released, prereleased ]

jobs:
  build:
    name: Compile and Push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build documentation
        run: ./gradlew dokkaHtml --no-configuration-cache

      - name: Push to docs branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: kdocs
